<?php
        //******************** 配置信息 ********************************
        $smtpserver = "mail.loongson.cn";//SMTP服务器
        $smtpserverport = 25;//SMTP服务器端口
        $smtpusermail = "jinguojie@loongson.cn";//SMTP服务器的用户邮箱
        $smtpuser = "jinguojie@loongson.cn";//SMTP服务器的用户帐号，注：部分邮箱只需@前面的用户名
        $smtppass = "Guojie81";//SMTP服务器的用户密码
        $mailtype = "HTML";//邮件格式（HTML/TXT）,TXT为文本邮件
?>
